# -*- coding: utf-8 -*-
"""problem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c8S-NWKAC2HIPs05V-lG77FLNvJe5h9L
"""

name = input("Enter Your name \n")
print(name + " is giving genese online test")